dev:
  debug: false
  version: 0.1
  maintainer:
    name: Théo Vidal
    link: exybore@becauseofprog.fr
bot:
  name: XBOP
  id: 796457702666534972
  illustration: https://cdn.discordapp.com/app-icons/796457702666534972/88a99cba60ccf586d54a1d38f450e8f9.png?size=256
  website: https://github.com/theovidal/105quiz
  prefix: "!"
  color: 16750457
categories:
  default:
    name: Non classé
    emoji: x
cache:
  address: localhost
  port: 6379
